import type { Category } from '../types'

export const CATEGORY_ICONS = [
  'utensils',
  'shopping-cart',
  'shopping-bag',
  'car',
  'bus',
  'fuel',
  'home',
  'zap',
  'wifi',
  'smartphone',
  'heart-pulse',
  'graduation-cap',
  'plane',
  'gamepad-2',
  'film',
  'music',
  'dumbbell',
  'gift',
  'coffee',
  'baby',
  'paw-print',
  'shirt',
  'scissors',
  'briefcase',
  'landmark',
  'piggy-bank',
  'trending-up',
  'banknote',
  'wallet',
  'hand-coins',
  'receipt',
  'circle-dollar-sign',
] as const

export const CATEGORY_COLORS = [
  '#ef4444',
  '#f97316',
  '#f59e0b',
  '#eab308',
  '#84cc16',
  '#22c55e',
  '#10b981',
  '#14b8a6',
  '#06b6d4',
  '#0ea5e9',
  '#3b82f6',
  '#6366f1',
  '#8b5cf6',
  '#a855f7',
  '#d946ef',
  '#ec4899',
  '#f43f5e',
  '#64748b',
] as const

export const DEFAULT_CATEGORIES: Category[] = [
  // Expenses
  { id: 'cat-food', name: 'Food & Dining', type: 'expense', icon: 'utensils', color: '#f97316' },
  { id: 'cat-groceries', name: 'Groceries', type: 'expense', icon: 'shopping-cart', color: '#22c55e' },
  { id: 'cat-transport', name: 'Transport', type: 'expense', icon: 'car', color: '#3b82f6' },
  { id: 'cat-housing', name: 'Housing & Rent', type: 'expense', icon: 'home', color: '#8b5cf6' },
  { id: 'cat-utilities', name: 'Utilities', type: 'expense', icon: 'zap', color: '#eab308' },
  { id: 'cat-shopping', name: 'Shopping', type: 'expense', icon: 'shopping-bag', color: '#ec4899' },
  { id: 'cat-health', name: 'Health', type: 'expense', icon: 'heart-pulse', color: '#ef4444' },
  { id: 'cat-entertainment', name: 'Entertainment', type: 'expense', icon: 'film', color: '#06b6d4' },
  { id: 'cat-education', name: 'Education', type: 'expense', icon: 'graduation-cap', color: '#14b8a6' },
  { id: 'cat-travel', name: 'Travel', type: 'expense', icon: 'plane', color: '#0ea5e9' },
  { id: 'cat-subscriptions', name: 'Subscriptions', type: 'expense', icon: 'smartphone', color: '#a855f7' },
  { id: 'cat-other-exp', name: 'Other', type: 'expense', icon: 'receipt', color: '#64748b' },
  // Income
  { id: 'cat-salary', name: 'Salary', type: 'income', icon: 'briefcase', color: '#10b981' },
  { id: 'cat-freelance', name: 'Freelance', type: 'income', icon: 'hand-coins', color: '#22c55e' },
  { id: 'cat-investment', name: 'Investments', type: 'income', icon: 'trending-up', color: '#0ea5e9' },
  { id: 'cat-gift-income', name: 'Gifts', type: 'income', icon: 'gift', color: '#ec4899' },
  { id: 'cat-other-inc', name: 'Other Income', type: 'income', icon: 'circle-dollar-sign', color: '#64748b' },
]

export const DEFAULT_ACCOUNTS = ['Cash', 'Bank Account', 'Credit Card', 'Savings']
