import {
  AlertTriangle,
  ArrowDownRight,
  ArrowUpRight,
  Baby,
  Banknote,
  Briefcase,
  Bus,
  Car,
  CircleDollarSign,
  Coffee,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gauge,
  GraduationCap,
  Gift,
  HandCoins,
  HeartPulse,
  Home,
  Landmark,
  Music,
  PawPrint,
  PieChart,
  PiggyBank,
  Plane,
  Receipt,
  Repeat,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Target,
  TrendingDown,
  TrendingUp,
  Utensils,
  Wallet,
  Wifi,
  Zap,
  type LucideIcon,
} from 'lucide-react'

const MAP: Record<string, LucideIcon> = {
  utensils: Utensils,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  car: Car,
  bus: Bus,
  fuel: Fuel,
  home: Home,
  zap: Zap,
  wifi: Wifi,
  smartphone: Smartphone,
  'heart-pulse': HeartPulse,
  'graduation-cap': GraduationCap,
  plane: Plane,
  'gamepad-2': Gamepad2,
  film: Film,
  music: Music,
  dumbbell: Dumbbell,
  gift: Gift,
  coffee: Coffee,
  baby: Baby,
  'paw-print': PawPrint,
  shirt: Shirt,
  scissors: Scissors,
  briefcase: Briefcase,
  landmark: Landmark,
  'piggy-bank': PiggyBank,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  banknote: Banknote,
  wallet: Wallet,
  'hand-coins': HandCoins,
  receipt: Receipt,
  'circle-dollar-sign': CircleDollarSign,
  // insight icons
  'alert-triangle': AlertTriangle,
  'arrow-up-right': ArrowUpRight,
  'arrow-down-right': ArrowDownRight,
  gauge: Gauge,
  'pie-chart': PieChart,
  target: Target,
  repeat: Repeat,
  sparkles: Sparkles,
}

export function CategoryIcon({
  icon,
  className,
}: {
  icon: string
  className?: string
}) {
  const Icon = MAP[icon] ?? Receipt
  return <Icon className={className} />
}

export function hasIcon(icon: string): boolean {
  return icon in MAP
}
