import {
  ShoppingCart,
  Utensils,
  Car,
  Home,
  Plug,
  ShoppingBag,
  Clapperboard,
  HeartPulse,
  GraduationCap,
  Plane,
  Repeat,
  Briefcase,
  Laptop,
  TrendingUp,
  Gift,
  Wallet,
  Coffee,
  Dumbbell,
  Gamepad2,
  Book,
  Fuel,
  Pizza,
  Baby,
  Dog,
  Phone,
  Wifi,
  Droplet,
  Zap,
  PiggyBank,
  Ellipsis,
  CircleDollarSign,
  type LucideIcon,
} from 'lucide-react'

const ICON_MAP: Record<string, LucideIcon> = {
  'shopping-cart': ShoppingCart,
  utensils: Utensils,
  car: Car,
  home: Home,
  plug: Plug,
  'shopping-bag': ShoppingBag,
  clapperboard: Clapperboard,
  'heart-pulse': HeartPulse,
  'graduation-cap': GraduationCap,
  plane: Plane,
  repeat: Repeat,
  briefcase: Briefcase,
  laptop: Laptop,
  'trending-up': TrendingUp,
  gift: Gift,
  wallet: Wallet,
  coffee: Coffee,
  dumbbell: Dumbbell,
  'gamepad-2': Gamepad2,
  book: Book,
  fuel: Fuel,
  pizza: Pizza,
  baby: Baby,
  dog: Dog,
  phone: Phone,
  wifi: Wifi,
  droplet: Droplet,
  zap: Zap,
  'piggy-bank': PiggyBank,
  ellipsis: Ellipsis,
}

export function CategoryIcon({
  name,
  className,
}: {
  name: string | undefined
  className?: string
}) {
  const Icon = (name && ICON_MAP[name]) || CircleDollarSign
  return <Icon className={className} />
}
